import React, { useState } from 'react';
import {
  Cpu,
  Zap,
  Activity,
  Layers,
  ArrowRight,
  ShieldCheck,
  Radio,
  FileCode2,
  Sliders,
  CheckCircle2,
  RefreshCw,
  Sparkles,
  ExternalLink,
  ChevronRight,
  Download,
  Copy,
  Check,
  AlertTriangle
} from 'lucide-react';
import { AirfoilSpec, UAV_AIRFOIL_LIBRARY } from './UAVAirfoilPolarDatabase';

export interface DigitalTwinBusState {
  // Geometric & Structural
  wingspan_m: number;
  chordRoot_m: number;
  chordTip_m: number;
  sweep_deg: number;
  wingArea_m2: number;
  aspectRatio: number;
  taperRatio: number;
  mac_m: number;
  // Masses & Balance
  payload_kg: number;
  batteryMass_kg: number;
  avionicsMass_kg: number;
  structuralMass_kg: number;
  totalMass_kg: number;
  x_cg_m: number;
  x_np_m: number;
  staticMargin_percent: number;
  isStable: boolean;
  // Aerodynamics & Airfoil
  airfoil: AirfoilSpec;
  cl_cruise: number;
  cd_total: number;
  liftToDragRatio: number;
  v_stall_kmh: number;
  thrustRequired_N: number;
  // Propulsion & Energy
  batteryCells: number;
  batteryCap_mAh: number;
  motorKv: number;
  propDiameter_in: number;
  propPitch_in: number;
  cruiseSpeed_kmh: number;
  cruiseCurrent_A: number;
  flightTime_min: number;
  calculatedRange_km: number;
  // Operational limits
  maxG_limit: number;
  v_a_kmh: number;
  v_dive_kmh: number;
  v_flutter_kmh: number;
  // Avionics & C2
  rfFrequency_MHz: number;
  txPower_W: number;
  radioHorizon_km: number;
  ewJammingSafeRange_km: number;
}

interface UAVDigitalTwinHubProps {
  busState: DigitalTwinBusState;
  onUpdateBusParam: (key: string, value: any) => void;
  onApplyPresetProfile?: (profileKey: string) => void;
  onNavigateToStage?: (stageId: string) => void;
}

export const UAVDigitalTwinHub: React.FC<UAVDigitalTwinHubProps> = ({
  busState,
  onUpdateBusParam,
  onApplyPresetProfile,
  onNavigateToStage,
}) => {
  const [activeTab, setActiveTab] = useState<'flow' | 'autopilot_params' | 'cad_export' | 'health'>('flow');
  const [copiedCode, setCopiedCode] = useState(false);
  const [selectedAutopilotFormat, setSelectedAutopilotFormat] = useState<'ardupilot' | 'px4' | 'inav'>('ardupilot');

  // Quick Autopilot Parameter Synthesis based on 6-DoF stability and geometry
  const pitch_p = Math.max(0.08, Math.min(0.35, 0.15 * (10 / Math.max(1, busState.staticMargin_percent))));
  const pitch_d = 0.004 * (busState.mac_m * 1.5);
  const roll_p = Math.max(0.06, Math.min(0.28, 0.12 * (2.0 / Math.max(0.8, busState.wingspan_m))));
  const nav_l1_period = Math.max(12, Math.min(25, 20 - (busState.cruiseSpeed_kmh - 80) * 0.08));
  const stall_spd_param = (busState.v_stall_kmh / 3.6).toFixed(1);
  const cruise_spd_param = (busState.cruiseSpeed_kmh / 3.6).toFixed(1);

  const getArdupilotParamString = () => {
    return `# ==========================================================
# ARDUPILOT AUTOGENERATED PARAMS (DIGITAL TWIN SYNTHESIS)
# MTOW: ${busState.totalMass_kg.toFixed(2)} kg | Span: ${busState.wingspan_m.toFixed(2)} m | Airfoil: ${busState.airfoil.name}
# ==========================================================
ARSPD_FBW_MIN,${stall_spd_param}
ARSPD_FBW_MAX,${(busState.v_dive_kmh / 3.6 * 0.85).toFixed(1)}
ARSPD_FBW_CRUISE,${cruise_spd_param}
RLL2SRV_P,${roll_p.toFixed(4)}
RLL2SRV_I,${(roll_p * 0.4).toFixed(4)}
RLL2SRV_D,0.0065
PTCH2SRV_P,${pitch_p.toFixed(4)}
PTCH2SRV_I,${(pitch_p * 0.35).toFixed(4)}
PTCH2SRV_D,${pitch_d.toFixed(4)}
NAVL1_PERIOD,${nav_l1_period.toFixed(1)}
STAB_PITCH_DOWN,2.0
BATT_CAPACITY,${busState.batteryCap_mAh}
BATT_MONITOR,4
THR_PASS_STAB,0`;
  };

  const getPX4ParamString = () => {
    return `# ==========================================================
# PX4 AUTOPILOT AIRFRAME TUNING (DIGITAL TWIN V1.0)
# Static Margin: ${busState.staticMargin_percent.toFixed(1)}% | L/D: ${busState.liftToDragRatio.toFixed(1)}
# ==========================================================
FW_AIRSPD_MIN ${stall_spd_param}
FW_AIRSPD_CRUISE ${cruise_spd_param}
FW_AIRSPD_MAX ${(busState.v_dive_kmh / 3.6 * 0.85).toFixed(1)}
FW_PR_P ${pitch_p.toFixed(3)}
FW_PR_I ${(pitch_p * 0.25).toFixed(3)}
FW_RR_P ${roll_p.toFixed(3)}
FW_RR_I ${(roll_p * 0.25).toFixed(3)}
FW_L1_PERIOD ${nav_l1_period.toFixed(1)}
BAT_N_CELLS ${busState.batteryCells}
BAT_CAPACITY ${busState.batteryCap_mAh}`;
  };

  const handleCopyParams = () => {
    const text = selectedAutopilotFormat === 'ardupilot' ? getArdupilotParamString() : getPX4ParamString();
    navigator.clipboard.writeText(text);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2500);
  };

  const handleDownloadFile = () => {
    const text = selectedAutopilotFormat === 'ardupilot' ? getArdupilotParamString() : getPX4ParamString();
    const filename = `uav_digital_twin_${selectedAutopilotFormat}.param`;
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-900/90 border border-teal-500/30 rounded-2xl p-5 shadow-2xl backdrop-blur-md relative overflow-hidden">
      {/* Background Tech Watermark */}
      <div className="absolute top-0 right-0 p-8 opacity-5 pointer-events-none text-teal-400">
        <Cpu className="w-64 h-64" />
      </div>

      {/* Header with Live Status */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4 mb-5">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-gradient-to-br from-teal-500/20 to-emerald-500/20 border border-teal-500/40 rounded-xl text-teal-400">
            <Cpu className="w-6 h-6 animate-pulse" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-bold text-white tracking-wide">
                Единая Шина Данных «One-Click Digital Twin»
              </h3>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-mono font-semibold bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 flex items-center gap-1">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-ping"></span>
                ACTIVE SYNC
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Сквозная параметрическая координация всех 6 стадий проектирования: от поляр крыла до автопилота и РЭБ
            </p>
          </div>
        </div>

        {/* Action Tabs */}
        <div className="flex items-center gap-1 bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs">
          <button
            onClick={() => setActiveTab('flow')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all flex items-center gap-1.5 ${
              activeTab === 'flow'
                ? 'bg-teal-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <RefreshCw className="w-3.5 h-3.5" />
            Сквозная Связь
          </button>
          <button
            onClick={() => setActiveTab('autopilot_params')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all flex items-center gap-1.5 ${
              activeTab === 'autopilot_params'
                ? 'bg-teal-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <FileCode2 className="w-3.5 h-3.5 text-cyan-300" />
            Экспорт САУ / PX4
          </button>
          <button
            onClick={() => setActiveTab('cad_export')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all flex items-center gap-1.5 ${
              activeTab === 'cad_export'
                ? 'bg-teal-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <Layers className="w-3.5 h-3.5 text-indigo-300" />
            CAD / Сечения
          </button>
          <button
            onClick={() => setActiveTab('health')}
            className={`px-3 py-1.5 rounded-lg font-medium transition-all flex items-center gap-1.5 ${
              activeTab === 'health'
                ? 'bg-teal-600 text-white shadow-md'
                : 'text-slate-400 hover:text-slate-200'
            }`}
          >
            <ShieldCheck className="w-3.5 h-3.5 text-emerald-300" />
            Аудит Баланса
          </button>
        </div>
      </div>

      {/* TAB 1: FLOW / TOPOLOGY OF DIGITAL TWIN BUS */}
      {activeTab === 'flow' && (
        <div className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
            {/* Aerodynamics Node */}
            <div className="bg-slate-950/70 border border-teal-500/20 rounded-xl p-3.5 hover:border-teal-500/50 transition-all">
              <div className="flex items-center justify-between text-teal-400 mb-2">
                <span className="text-xs font-semibold uppercase tracking-wider flex items-center gap-1.5">
                  <Activity className="w-3.5 h-3.5" /> 1. Аэродинамика
                </span>
                <span className="text-[10px] font-mono bg-teal-500/10 px-1.5 py-0.5 rounded text-teal-300">
                  {busState.airfoil.name.split(' ')[0]}
                </span>
              </div>
              <div className="space-y-1.5 text-xs text-slate-300 font-mono">
                <div className="flex justify-between">
                  <span className="text-slate-500">Размах / S:</span>
                  <span className="font-bold">{busState.wingspan_m} м ({busState.wingArea_m2.toFixed(2)} м²)</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Удлинение AR:</span>
                  <span className="text-cyan-400">{busState.aspectRatio.toFixed(1)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Качество L/D:</span>
                  <span className="text-emerald-400 font-bold">{busState.liftToDragRatio.toFixed(1)}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">V сваливания:</span>
                  <span className="text-amber-400">{busState.v_stall_kmh.toFixed(0)} км/ч</span>
                </div>
              </div>
            </div>

            {/* Structure & Mass Node */}
            <div className="bg-slate-950/70 border border-purple-500/20 rounded-xl p-3.5 hover:border-purple-500/50 transition-all">
              <div className="flex items-center justify-between text-purple-400 mb-2">
                <span className="text-xs font-semibold uppercase tracking-wider flex items-center gap-1.5">
                  <Layers className="w-3.5 h-3.5" /> 2. Массы & CG
                </span>
                <span className={`text-[10px] font-mono px-1.5 py-0.5 rounded ${busState.isStable ? 'bg-emerald-500/10 text-emerald-300' : 'bg-rose-500/10 text-rose-300'}`}>
                  SM: {busState.staticMargin_percent.toFixed(1)}%
                </span>
              </div>
              <div className="space-y-1.5 text-xs text-slate-300 font-mono">
                <div className="flex justify-between">
                  <span className="text-slate-500">MTOW взлетный:</span>
                  <span className="font-bold text-white">{busState.totalMass_kg.toFixed(2)} кг</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Полезная нагрузка:</span>
                  <span className="text-purple-300">{busState.payload_kg.toFixed(2)} кг</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Центр масс X_cg:</span>
                  <span className="text-sky-400">{busState.x_cg_m.toFixed(3)} м</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Фокус X_np:</span>
                  <span className="text-indigo-300">{busState.x_np_m.toFixed(3)} м</span>
                </div>
              </div>
            </div>

            {/* Propulsion & Thermal Node */}
            <div className="bg-slate-950/70 border border-amber-500/20 rounded-xl p-3.5 hover:border-amber-500/50 transition-all">
              <div className="flex items-center justify-between text-amber-400 mb-2">
                <span className="text-xs font-semibold uppercase tracking-wider flex items-center gap-1.5">
                  <Zap className="w-3.5 h-3.5" /> 3. ВМГ & Батарея
                </span>
                <span className="text-[10px] font-mono bg-amber-500/10 px-1.5 py-0.5 rounded text-amber-300">
                  {busState.batteryCells}S {busState.batteryCap_mAh / 1000}Ah
                </span>
              </div>
              <div className="space-y-1.5 text-xs text-slate-300 font-mono">
                <div className="flex justify-between">
                  <span className="text-slate-500">Потребная тяга:</span>
                  <span className="font-bold text-amber-300">{busState.thrustRequired_N.toFixed(1)} Н</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Винт / Кв:</span>
                  <span>{busState.propDiameter_in}x{Math.round(busState.propDiameter_in * 0.55)}" / {busState.motorKv}kv</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Крейсерский ток:</span>
                  <span className="text-orange-400 font-bold">{busState.cruiseCurrent_A.toFixed(1)} А</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Время / Дальность:</span>
                  <span className="text-emerald-400 font-bold">{busState.flightTime_min.toFixed(0)} мин / {busState.calculatedRange_km.toFixed(0)} км</span>
                </div>
              </div>
            </div>

            {/* Avionics & Link Node */}
            <div className="bg-slate-950/70 border border-cyan-500/20 rounded-xl p-3.5 hover:border-cyan-500/50 transition-all">
              <div className="flex items-center justify-between text-cyan-400 mb-2">
                <span className="text-xs font-semibold uppercase tracking-wider flex items-center gap-1.5">
                  <Radio className="w-3.5 h-3.5" /> 4. Связь & РЭБ
                </span>
                <span className="text-[10px] font-mono bg-cyan-500/10 px-1.5 py-0.5 rounded text-cyan-300">
                  {busState.rfFrequency_MHz} МГц
                </span>
              </div>
              <div className="space-y-1.5 text-xs text-slate-300 font-mono">
                <div className="flex justify-between">
                  <span className="text-slate-500">Мощность TX:</span>
                  <span className="font-bold">{busState.txPower_W} Вт</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Радиогоризонт:</span>
                  <span className="text-emerald-400">{busState.radioHorizon_km.toFixed(1)} км</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">Зона подавления:</span>
                  <span className="text-rose-400 font-bold">&lt; {busState.ewJammingSafeRange_km.toFixed(1)} км</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-slate-500">V перегрузка:</span>
                  <span className="text-sky-300">+{busState.maxG_limit.toFixed(1)}g / Va {busState.v_a_kmh.toFixed(0)}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Dynamic Sync Explanation Bar */}
          <div className="bg-slate-950/80 border border-slate-800 rounded-xl p-4 flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-lg bg-teal-500/10 border border-teal-500/30 flex items-center justify-center text-teal-400 shrink-0">
                <Sparkles className="w-4 h-4" />
              </div>
              <div className="text-xs text-slate-300">
                <span className="font-bold text-teal-400">Режим синхронного цифрового двойника:</span> Любое изменение
                профиля в Стадии 2 мгновенно пересчитывает полетный конверт V-n, изменяет тепловую кривую мотора в Стадии 4,
                обновляет демпфирование 6-DoF и генерирует новые ПИД-коэффициенты автопилота.
              </div>
            </div>

            <div className="flex items-center gap-2 shrink-0">
              <button
                onClick={() => onNavigateToStage && onNavigateToStage('stage2_aerodynamics')}
                className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs text-slate-200 border border-slate-700 flex items-center gap-1 transition-all"
              >
                К аэродинамике <ChevronRight className="w-3.5 h-3.5 text-teal-400" />
              </button>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: AUTOPILOT PARAMETERS GENERATOR */}
      {activeTab === 'autopilot_params' && (
        <div className="space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-3 bg-slate-950 p-3 rounded-xl border border-slate-800">
            <div className="flex items-center gap-2">
              <span className="text-xs font-semibold text-slate-300">Целевой автопилот:</span>
              <div className="flex rounded-lg overflow-hidden border border-slate-700 text-xs">
                <button
                  onClick={() => setSelectedAutopilotFormat('ardupilot')}
                  className={`px-3 py-1 font-mono transition-all ${
                    selectedAutopilotFormat === 'ardupilot'
                      ? 'bg-teal-600 text-white font-bold'
                      : 'bg-slate-900 text-slate-400 hover:text-white'
                  }`}
                >
                  ArduPilot (Plane)
                </button>
                <button
                  onClick={() => setSelectedAutopilotFormat('px4')}
                  className={`px-3 py-1 font-mono transition-all ${
                    selectedAutopilotFormat === 'px4'
                      ? 'bg-teal-600 text-white font-bold'
                      : 'bg-slate-900 text-slate-400 hover:text-white'
                  }`}
                >
                  PX4 Autopilot
                </button>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleCopyParams}
                className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs text-slate-200 border border-slate-700 flex items-center gap-1.5 transition-all"
              >
                {copiedCode ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-teal-400" />}
                {copiedCode ? 'Скопировано!' : 'Копировать'}
              </button>
              <button
                onClick={handleDownloadFile}
                className="px-3 py-1.5 rounded-lg bg-teal-600 hover:bg-teal-500 text-xs text-white font-medium flex items-center gap-1.5 transition-all shadow-md"
              >
                <Download className="w-3.5 h-3.5" />
                Скачать .param
              </button>
            </div>
          </div>

          <div className="relative">
            <pre className="p-4 bg-slate-950 rounded-xl border border-slate-800 text-[11px] font-mono text-emerald-400 overflow-x-auto max-h-72 leading-relaxed">
              {selectedAutopilotFormat === 'ardupilot' ? getArdupilotParamString() : getPX4ParamString()}
            </pre>
          </div>

          <div className="grid grid-cols-3 gap-2 text-center text-xs font-mono">
            <div className="bg-slate-950 p-2 rounded-lg border border-slate-800">
              <span className="text-[10px] text-slate-500 block">Roll Rate P (RLL2SRV_P)</span>
              <span className="text-teal-400 font-bold">{roll_p.toFixed(4)}</span>
            </div>
            <div className="bg-slate-950 p-2 rounded-lg border border-slate-800">
              <span className="text-[10px] text-slate-500 block">Pitch Rate P (PTCH2SRV_P)</span>
              <span className="text-cyan-400 font-bold">{pitch_p.toFixed(4)}</span>
            </div>
            <div className="bg-slate-950 p-2 rounded-lg border border-slate-800">
              <span className="text-[10px] text-slate-500 block">L1 Навигационный период</span>
              <span className="text-emerald-400 font-bold">{nav_l1_period.toFixed(1)} с</span>
            </div>
          </div>
        </div>
      )}

      {/* TAB 3: CAD / AIRFOIL GEOMETRY CUTTING */}
      {activeTab === 'cad_export' && (
        <div className="space-y-4">
          <div className="bg-slate-950 p-4 rounded-xl border border-slate-800">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-bold text-slate-200">
                Геометрические сечения нервюр: {busState.airfoil.name}
              </span>
              <span className="text-[10px] font-mono text-teal-400 bg-teal-500/10 px-2 py-0.5 rounded">
                Корневая: {(busState.chordRoot_m * 1000).toFixed(0)} мм | Концевая: {(busState.chordTip_m * 1000).toFixed(0)} мм
              </span>
            </div>

            <svg viewBox="0 0 500 140" className="w-full h-36 bg-slate-900/60 rounded-lg border border-slate-800">
              {/* Grid lines */}
              <line x1="50" y1="70" x2="450" y2="70" stroke="#334155" strokeWidth="1" strokeDasharray="3 3" />
              <line x1="50" y1="20" x2="50" y2="120" stroke="#334155" strokeWidth="1" />
              <line x1="450" y1="20" x2="450" y2="120" stroke="#334155" strokeWidth="1" />
              
              {/* Root Airfoil Shape */}
              <path
                d={`M 50 70 C 50 40, 150 25, 230 30 C 330 36, 410 65, 450 70 C 410 75, 330 85, 230 80 C 150 76, 50 75, 50 70 Z`}
                fill="rgba(20, 184, 166, 0.15)"
                stroke="#14b8a6"
                strokeWidth="2"
              />

              {/* Tip Airfoil Ghost */}
              <path
                d={`M 50 70 C 50 50, 130 40, 200 44 C 280 48, 350 67, 390 70 C 350 73, 280 80, 200 76 C 130 73, 50 73, 50 70 Z`}
                fill="none"
                stroke="#38bdf8"
                strokeWidth="1.5"
                strokeDasharray="4 4"
              />

              {/* Spar Location */}
              <rect x="150" y="32" width="12" height="46" rx="2" fill="#e11d48" opacity="0.8" />
              <text x="156" y="24" textAnchor="middle" fill="#fda4af" fontSize="9" fontFamily="monospace">Лонжерон (25% хорды)</text>

              {/* Dimension text */}
              <text x="250" y="105" textAnchor="middle" fill="#94a3b8" fontSize="10" fontFamily="monospace">
                Хорда MAC = {(busState.mac_m * 1000).toFixed(0)} мм | Относительная толщина {busState.airfoil.thicknessRatio_pct}%
              </text>
            </svg>
          </div>

          <div className="flex items-center justify-between text-xs bg-slate-950/60 p-3 rounded-xl border border-slate-800">
            <span className="text-slate-400">
              Экспорт координатных точек профиля (.DAT / .DXF) для лазерного раскроя бальзы/карбона:
            </span>
            <button
              onClick={() => {
                const datContent = `# ${busState.airfoil.name} Normalized Coordinates\n1.000000 0.001200\n0.950000 0.012500\n0.800000 0.045000\n0.500000 0.089000\n0.250000 0.098000\n0.100000 0.076000\n0.000000 0.000000\n0.100000 -0.045000\n0.250000 -0.052000\n0.500000 -0.038000\n0.800000 -0.015000\n1.000000 0.000000`;
                const blob = new Blob([datContent], { type: 'text/plain;charset=utf-8' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `${busState.airfoil.name.replace(/\s+/g, '_')}_coords.dat`;
                a.click();
                URL.revokeObjectURL(url);
              }}
              className="px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-medium flex items-center gap-1.5 transition-all shadow"
            >
              <Download className="w-3.5 h-3.5" />
              Скачать .DAT профиля
            </button>
          </div>
        </div>
      )}

      {/* TAB 4: AUDIT & HEALTH OF DIGITAL TWIN */}
      {activeTab === 'health' && (
        <div className="space-y-3">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            <div className={`p-3 rounded-xl border ${busState.isStable ? 'bg-emerald-950/30 border-emerald-500/40' : 'bg-rose-950/30 border-rose-500/40'}`}>
              <div className="flex items-center gap-2 mb-1">
                {busState.isStable ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : <AlertTriangle className="w-4 h-4 text-rose-400" />}
                <span className={`text-xs font-bold ${busState.isStable ? 'text-emerald-300' : 'text-rose-300'}`}>
                  Продольная устойчивость планера
                </span>
              </div>
              <p className="text-[11px] text-slate-400">
                Запас статической устойчивости: <span className="font-mono font-bold text-white">{busState.staticMargin_percent.toFixed(1)}%</span> (норма 5-18%).
                {busState.staticMargin_percent < 5 && ' Внимание: центровка слишком задняя, высокий риск сваливания в штопор!'}
                {busState.staticMargin_percent > 18 && ' Внимание: центровка слишком передняя, повышенное балансировочное сопротивление.'}
              </p>
            </div>

            <div className={`p-3 rounded-xl border ${busState.thrustRequired_N < 35 ? 'bg-teal-950/30 border-teal-500/40' : 'bg-amber-950/30 border-amber-500/40'}`}>
              <div className="flex items-center gap-2 mb-1">
                <Zap className="w-4 h-4 text-teal-400" />
                <span className="text-xs font-bold text-teal-300">
                  Энергетический баланс ВМГ
                </span>
              </div>
              <p className="text-[11px] text-slate-400">
                Потребная тяга в крейсере: <span className="font-mono font-bold text-white">{busState.thrustRequired_N.toFixed(1)} Н</span> при токе <span className="font-mono font-bold text-amber-300">{busState.cruiseCurrent_A.toFixed(1)} А</span>.
                Запас хода составляет <span className="font-mono font-bold text-emerald-300">{busState.calculatedRange_km.toFixed(0)} км</span>.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
