import React, { useState, useMemo } from 'react';
import {
  FileCode,
  Download,
  Copy,
  Check,
  Cpu,
  Layers,
  FileSpreadsheet,
  Boxes,
  Zap,
  Sliders,
  Settings,
  Scissors,
  Share2,
  FileText,
  AlertCircle,
  ExternalLink,
  ChevronRight
} from 'lucide-react';
import { DigitalTwinBusState } from './UAVDigitalTwinHub';

interface UAVEngineeringArtifactsExporterProps {
  busState: DigitalTwinBusState;
}

export type ExportFormat =
  | 'ardupilot_param'
  | 'px4_params'
  | 'inav_cli'
  | 'dxf_ribs'
  | 'dat_selig'
  | 'openscad_wing'
  | 'wiring_bom_json'
  | 'matlab_simulink';

export const UAVEngineeringArtifactsExporter: React.FC<UAVEngineeringArtifactsExporterProps> = ({
  busState,
}) => {
  const [selectedFormat, setSelectedFormat] = useState<ExportFormat>('ardupilot_param');
  const [copied, setCopied] = useState(false);
  const [sparPositionPct, setSparPositionPct] = useState(25);
  const [ribCount, setRibCount] = useState(6);
  const [skinThicknessMm, setSkinThicknessMm] = useState(1.5);
  const [sparHoleDiaMm, setSparHoleDiaMm] = useState(8);

  // Dynamic calculations for Control & Autopilot
  const pitch_p = Math.max(0.08, Math.min(0.35, 0.15 * (10 / Math.max(1, busState.staticMargin_percent))));
  const pitch_i = pitch_p * 0.35;
  const pitch_d = 0.004 * (busState.mac_m * 1.5);
  const roll_p = Math.max(0.06, Math.min(0.28, 0.12 * (2.0 / Math.max(0.8, busState.wingspan_m))));
  const roll_i = roll_p * 0.4;
  const roll_d = 0.0065;
  const nav_l1_period = Math.max(12, Math.min(25, 20 - (busState.cruiseSpeed_kmh - 80) * 0.08));
  const stall_spd_ms = (busState.v_stall_kmh / 3.6).toFixed(1);
  const cruise_spd_ms = (busState.cruiseSpeed_kmh / 3.6).toFixed(1);
  const max_spd_ms = (busState.v_dive_kmh / 3.6 * 0.85).toFixed(1);

  // 1. ArduPilot Parameters (.param)
  const generateArduPilotParam = useMemo(() => {
    return `# ==============================================================================
# ARDUPILOT PLANE AUTOGENERATED TUNING PROFILE
# Generator: AeroDesign Studio Pro UAV Master Pipeline
# Airframe: MTOW ${busState.totalMass_kg.toFixed(2)} kg | Wingspan ${busState.wingspan_m.toFixed(2)} m | Airfoil: ${busState.airfoil.name}
# ==============================================================================
FORMAT_VERSION,1
# --- SPEED & AIRSPEED LIMITS ---
ARSPD_ENABLE,1
ARSPD_TYPE,1
ARSPD_USE,1
ARSPD_FBW_MIN,${stall_spd_ms}
ARSPD_FBW_MAX,${max_spd_ms}
ARSPD_FBW_CRUISE,${cruise_spd_ms}
TRIM_ARSPD_CM,${Math.round(busState.cruiseSpeed_kmh / 3.6 * 100)}
MIN_GNDSPD_CM,700

# --- ROLL CONTROLLER (L1 & PIDs) ---
RLL2SRV_P,${roll_p.toFixed(5)}
RLL2SRV_I,${roll_i.toFixed(5)}
RLL2SRV_D,${roll_d.toFixed(5)}
RLL2SRV_RMAX,60.0
RLL2SRV_TCONST,0.45
LIM_ROLL_CD,4500

# --- PITCH CONTROLLER ---
PTCH2SRV_P,${pitch_p.toFixed(5)}
PTCH2SRV_I,${pitch_i.toFixed(5)}
PTCH2SRV_D,${pitch_d.toFixed(5)}
PTCH2SRV_RMAX,40.0
PTCH2SRV_TCONST,0.40
LIM_PITCH_MAX,2500
LIM_PITCH_MIN,-2000
STAB_PITCH_DOWN,2.0

# --- NAVIGATION & L1 ADAPTIVE TRACKING ---
NAVL1_PERIOD,${nav_l1_period.toFixed(2)}
NAVL1_DAMPING,0.75
NAVL1_XTRACK_I,0.02
WP_LOITER_RAD,60

# --- BATTERY & POWER MONITORING ---
BATT_MONITOR,4
BATT_CAPACITY,${busState.batteryCap_mAh}
BATT_ARM_VOLT,${(busState.batteryCells * 3.8).toFixed(1)}
BATT_CRT_VOLT,${(busState.batteryCells * 3.4).toFixed(1)}
BATT_LOW_VOLT,${(busState.batteryCells * 3.55).toFixed(1)}
THR_PASS_STAB,0
TKOFF_THR_MAX,100
`;
  }, [busState, roll_p, roll_i, roll_d, pitch_p, pitch_i, pitch_d, nav_l1_period, stall_spd_ms, cruise_spd_ms, max_spd_ms]);

  // 2. PX4 Autopilot Parameters
  const generatePX4Params = useMemo(() => {
    return `# ==============================================================================
# PX4 AUTOPILOT FIXED-WING PARAMETERS (AIRFRAME SYNTHESIS)
# Digital Twin Sync: Static Margin ${busState.staticMargin_percent.toFixed(1)}% | L/D = ${busState.liftToDragRatio.toFixed(1)}
# ==============================================================================
FW_AIRSPD_MIN ${stall_spd_ms}
FW_AIRSPD_CRUISE ${cruise_spd_ms}
FW_AIRSPD_MAX ${max_spd_ms}
FW_AIRSPD_TRIM ${cruise_spd_ms}
FW_AIRSPD_STALL ${stall_spd_ms}

# Rate & Attitude PIDs
FW_PR_P ${pitch_p.toFixed(4)}
FW_PR_I ${pitch_i.toFixed(4)}
FW_PR_D ${pitch_d.toFixed(5)}
FW_RR_P ${roll_p.toFixed(4)}
FW_RR_I ${roll_i.toFixed(4)}
FW_RR_D ${roll_d.toFixed(5)}
FW_L1_PERIOD ${nav_l1_period.toFixed(2)}
FW_L1_DAMPING 0.75

# Battery Specs
BAT_N_CELLS ${busState.batteryCells}
BAT_CAPACITY ${busState.batteryCap_mAh}
BAT_V_CHARGED 4.20
BAT_V_EMPTY 3.30
`;
  }, [busState, pitch_p, pitch_i, pitch_d, roll_p, roll_i, roll_d, nav_l1_period, stall_spd_ms, cruise_spd_ms, max_spd_ms]);

  // 3. INAV Fixed-Wing CLI Script
  const generateINAVCLI = useMemo(() => {
    return `# ==============================================================================
# INAV FIXED WING CLI CONFIGURATION
# ==============================================================================
feature AIRMODE
feature FW_AUTOTRIM
feature FW_LAUNCH

set nav_fw_min_velocity = ${Math.round(busState.v_stall_kmh / 3.6 * 100)}
set nav_fw_cruise_velocity = ${Math.round(busState.cruiseSpeed_kmh / 3.6 * 100)}
set nav_fw_max_velocity = ${Math.round(busState.v_dive_kmh / 3.6 * 85)}

set fw_p_pitch = ${Math.round(pitch_p * 100)}
set fw_i_pitch = ${Math.round(pitch_i * 100)}
set fw_d_pitch = ${Math.round(pitch_d * 1000)}

set fw_p_roll = ${Math.round(roll_p * 100)}
set fw_i_roll = ${Math.round(roll_i * 100)}
set fw_d_roll = ${Math.round(roll_d * 1000)}

set battery_capacity = ${busState.batteryCap_mAh}
set vbat_cell_count = ${busState.batteryCells}
save
`;
  }, [busState, pitch_p, pitch_i, pitch_d, roll_p, roll_i, roll_d]);

  // 4. DXF Ribs Generation (Auto CAD / CAM Laser Cut profile)
  const generateDXFRibs = useMemo(() => {
    // Generate DXF R12 format ASCII
    const chordRoot = busState.chordRoot_m * 1000;
    const chordTip = busState.chordTip_m * 1000;

    let dxf = `0\nSECTION\n2\nHEADER\n9\n$ACADVER\n1\nAC1006\n0\nENDSEC\n0\nSECTION\n2\nTABLES\n0\nENDSEC\n0\nSECTION\n2\nBLOCKS\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n`;

    // Function to generate rib polygon in DXF
    const addRibToDXF = (ribIdx: number, chord: number, yOffset: number) => {
      // Airfoil top/bottom approximation points (scaled to chord in mm)
      const points = [
        [0, 0],
        [chord * 0.05, chord * 0.038],
        [chord * 0.15, chord * 0.068],
        [chord * 0.30, chord * 0.082],
        [chord * 0.50, chord * 0.072],
        [chord * 0.70, chord * 0.048],
        [chord * 0.90, chord * 0.018],
        [chord, 0],
        [chord * 0.90, -chord * 0.012],
        [chord * 0.70, -chord * 0.024],
        [chord * 0.50, -chord * 0.032],
        [chord * 0.30, -chord * 0.038],
        [chord * 0.15, -chord * 0.030],
        [chord * 0.05, -chord * 0.018],
        [0, 0],
      ];

      // Draw polyline lines
      for (let i = 0; i < points.length - 1; i++) {
        dxf += `0\nLINE\n8\nRIB_${ribIdx + 1}\n10\n${points[i][0].toFixed(2)}\n20\n${(points[i][1] + yOffset).toFixed(2)}\n30\n0.0\n11\n${points[i+1][0].toFixed(2)}\n21\n${(points[i+1][1] + yOffset).toFixed(2)}\n31\n0.0\n`;
      }

      // Add Spar Circle Cutout
      const sparX = chord * (sparPositionPct / 100);
      dxf += `0\nCIRCLE\n8\nSPAR_HOLE\n10\n${sparX.toFixed(2)}\n20\n${yOffset.toFixed(2)}\n30\n0.0\n40\n${(sparHoleDiaMm / 2).toFixed(2)}\n`;

      // Text Label
      dxf += `0\nTEXT\n8\nLABELS\n10\n${(chord * 0.4).toFixed(2)}\n20\n${yOffset.toFixed(2)}\n30\n0.0\n40\n6.0\n1\nRIB #${ribIdx + 1} (Chord ${chord.toFixed(0)}mm)\n`;
    };

    for (let r = 0; r < ribCount; r++) {
      const frac = r / Math.max(1, ribCount - 1);
      const currentChord = chordRoot - frac * (chordRoot - chordTip);
      addRibToDXF(r, currentChord, r * 110);
    }

    dxf += `0\nENDSEC\n0\nEOF\n`;
    return dxf;
  }, [busState, sparPositionPct, ribCount, sparHoleDiaMm]);

  // 5. OpenSCAD 3D Wing Parametric Script
  const generateOpenSCAD = useMemo(() => {
    return `// ==============================================================================
// OPENSCAD PARAMETRIC UAV WING GENERATOR
// Airfoil: ${busState.airfoil.name} | Span: ${busState.wingspan_m}m
// ==============================================================================
$fn = 60;

wingspan_mm = ${busState.wingspan_m * 1000};
semi_span = wingspan_mm / 2;
root_chord = ${busState.chordRoot_m * 1000};
tip_chord = ${busState.chordTip_m * 1000};
sweep_deg = ${busState.sweep_deg};
spar_diameter = ${sparHoleDiaMm};
spar_pos_x = root_chord * ${sparPositionPct / 100};

module airfoil_profile(chord) {
    scale([chord, chord, 1]) {
        polygon(points=[
            [0.0, 0.0],
            [0.05, 0.038], [0.15, 0.068], [0.30, 0.082], 
            [0.50, 0.072], [0.70, 0.048], [0.90, 0.018], 
            [1.0, 0.0],
            [0.90, -0.012], [0.70, -0.024], [0.50, -0.032], 
            [0.30, -0.038], [0.15, -0.030], [0.05, -0.018],
            [0.0, 0.0]
        ]);
    }
}

module semi_wing() {
    difference() {
        hull() {
            // Root
            linear_extrude(height=1) airfoil_profile(root_chord);
            // Tip
            translate([tan(sweep_deg) * semi_span, 0, semi_span])
                linear_extrude(height=1) airfoil_profile(tip_chord);
        }
        // Carbon Spar Tunnel
        translate([spar_pos_x, 0, -10])
            cylinder(d=spar_diameter, h=semi_span + 20);
    }
}

// Render Left and Right Wings
semi_wing();
mirror([0, 0, 1]) semi_wing();
`;
  }, [busState, sparPositionPct, sparHoleDiaMm]);

  // 6. Wiring & Bill of Materials (BOM) JSON
  const generateBOMJSON = useMemo(() => {
    const escAmps = Math.ceil(busState.cruiseCurrent_A * 1.8 / 10) * 10;
    const wireGauge = busState.cruiseCurrent_A > 35 ? '12 AWG' : '14 AWG';

    const bom = {
      project: "UAV Master Engineering Pipeline",
      generated_at: new Date().toISOString(),
      flight_metrics: {
        mtow_kg: busState.totalMass_kg,
        cruise_speed_kmh: busState.cruiseSpeed_kmh,
        range_km: busState.calculatedRange_km,
        endurance_minutes: busState.flightTime_min,
        static_margin_pct: busState.staticMargin_percent
      },
      propulsion_system: {
        motor_kv: busState.motorKv,
        propeller: `${busState.propDiameter_in}x${Math.round(busState.propDiameter_in * 0.55)} inch`,
        battery: `${busState.batteryCells}S ${busState.batteryCap_mAh} mAh (${(busState.batteryMass_kg).toFixed(2)} kg)`,
        recommended_esc: `${escAmps}A OPTO / BLHeli_32`,
        main_power_lead: wireGauge,
        connector: busState.cruiseCurrent_A > 40 ? 'XT90-S (Anti-Spark)' : 'XT60H'
      },
      avionics_and_rf: {
        autopilot_hardware: 'Pixhawk 6X / Cube Orange / SpeedyBee F405-WING',
        c2_telemetry_frequency_mhz: busState.rfFrequency_MHz,
        c2_tx_power_w: busState.txPower_W,
        rf_safe_distance_km: busState.radioHorizon_km,
        airspeed_sensor: 'MS4525DO Pitot Tube (I2C)'
      },
      airframe_structural: {
        wingspan_m: busState.wingspan_m,
        wing_area_m2: busState.wingArea_m2,
        airfoil: busState.airfoil.name,
        spar_carbon_tube: `OD ${sparHoleDiaMm}mm Carbon Fiber Tube (Length: ${(busState.wingspan_m * 0.85 * 1000).toFixed(0)}mm)`,
        recommended_skin: '1.5mm Balsa / 200g Carbon Fiber composite'
      }
    };
    return JSON.stringify(bom, null, 2);
  }, [busState, sparHoleDiaMm]);

  // 7. Selig .DAT Coordinates
  const generateSeligDAT = useMemo(() => {
    return `${busState.airfoil.name} (T=${busState.airfoil.thicknessRatio_pct}%, Camber=${busState.airfoil.camber_pct}%)
 1.000000  0.001200
 0.950000  0.012500
 0.800000  0.045000
 0.650000  0.071000
 0.500000  0.089000
 0.350000  0.097000
 0.250000  0.098000
 0.150000  0.089000
 0.100000  0.076000
 0.050000  0.054000
 0.020000  0.033000
 0.000000  0.000000
 0.020000 -0.021000
 0.050000 -0.035000
 0.100000 -0.045000
 0.150000 -0.050000
 0.250000 -0.052000
 0.350000 -0.048000
 0.500000 -0.038000
 0.650000 -0.026000
 0.800000 -0.015000
 0.950000 -0.004000
 1.000000  0.000000`;
  }, [busState]);

  // 8. MATLAB / Simulink 6-DoF Script
  const generateMATLABScript = useMemo(() => {
    return `% ==============================================================================
% MATLAB / SIMULINK 6-DoF UAV LINEARIZATION SCRIPT
% Generated automatically by AeroDesign Studio Pro UAV Pipeline
% ==============================================================================
clear; clc;

% Mass & Inertia Tensor
m = ${busState.totalMass_kg.toFixed(3)}; % kg
b = ${busState.wingspan_m.toFixed(3)}; % m (Wingspan)
c_bar = ${busState.mac_m.toFixed(3)}; % m (MAC)
S = ${busState.wingArea_m2.toFixed(4)}; % m^2 (Wing Area)
rho = 1.225; % kg/m^3

% Dynamic Moments of Inertia (Calculated from mass distribution)
Ixx = ${(0.08 * busState.totalMass_kg * Math.pow(busState.wingspan_m, 2)).toFixed(4)};
Iyy = ${(0.05 * busState.totalMass_kg * Math.pow(busState.chordRoot_m * 2.5, 2)).toFixed(4)};
Izz = Ixx + Iyy;
Ixz = 0.002;

% Nominal Flight Conditions
V_cruise = ${(busState.cruiseSpeed_kmh / 3.6).toFixed(2)}; % m/s
q_bar = 0.5 * rho * V_cruise^2; % Pa

% Aerodynamic Stability Derivatives
CL_0 = ${(busState.cl_cruise * 0.6).toFixed(3)};
CL_alpha = ${(busState.airfoil.cl_max / 0.25).toFixed(2)}; % 1/rad
CD_0 = ${busState.cd_total.toFixed(4)};
Cm_0 = ${busState.airfoil.cm0.toFixed(3)};
Cm_alpha = ${(-busState.staticMargin_percent / 100 * (busState.airfoil.cl_max / 0.25)).toFixed(3)};
Cm_q = -12.5;

% State Space Matrix (Short Period Approximation)
% x = [w; q]
Z_w = -q_bar * S * (CL_alpha + CD_0) / (m * V_cruise);
Z_q = V_cruise;
M_w = q_bar * S * c_bar * (Cm_alpha) / (Iyy * V_cruise);
M_q = q_bar * S * c_bar^2 * Cm_q / (2 * Iyy * V_cruise);

A_sp = [Z_w, Z_q; M_w, M_q];
B_sp = [-q_bar * S * 0.4 / m; q_bar * S * c_bar * (-1.2) / Iyy];

sys_sp = ss(A_sp, B_sp, eye(2), zeros(2,1));
disp('Short-period Eigenvalues:');
damp(sys_sp);
`;
  }, [busState]);

  // Current Content & File info
  const currentArtifact = useMemo(() => {
    switch (selectedFormat) {
      case 'ardupilot_param':
        return {
          content: generateArduPilotParam,
          ext: '.param',
          mime: 'text/plain',
          name: `ardupilot_${busState.airfoil.name.replace(/\s+/g, '_')}.param`,
          language: 'ini'
        };
      case 'px4_params':
        return {
          content: generatePX4Params,
          ext: '.params',
          mime: 'text/plain',
          name: `px4_tuning_${busState.wingspan_m}m.params`,
          language: 'ini'
        };
      case 'inav_cli':
        return {
          content: generateINAVCLI,
          ext: '.txt',
          mime: 'text/plain',
          name: `inav_cli_config_${busState.wingspan_m}m.txt`,
          language: 'bash'
        };
      case 'dxf_ribs':
        return {
          content: generateDXFRibs,
          ext: '.dxf',
          mime: 'application/dxf',
          name: `wing_ribs_laser_cut_${ribCount}pcs.dxf`,
          language: 'text'
        };
      case 'openscad_wing':
        return {
          content: generateOpenSCAD,
          ext: '.scad',
          mime: 'text/plain',
          name: `parametric_wing_${busState.wingspan_m}m.scad`,
          language: 'javascript'
        };
      case 'wiring_bom_json':
        return {
          content: generateBOMJSON,
          ext: '.json',
          mime: 'application/json',
          name: `uav_electrical_bom_specs.json`,
          language: 'json'
        };
      case 'dat_selig':
        return {
          content: generateSeligDAT,
          ext: '.dat',
          mime: 'text/plain',
          name: `${busState.airfoil.name.replace(/\s+/g, '_')}.dat`,
          language: 'text'
        };
      case 'matlab_simulink':
        return {
          content: generateMATLABScript,
          ext: '.m',
          mime: 'text/plain',
          name: `uav_linear_stability_6dof.m`,
          language: 'matlab'
        };
    }
  }, [
    selectedFormat,
    generateArduPilotParam,
    generatePX4Params,
    generateINAVCLI,
    generateDXFRibs,
    generateOpenSCAD,
    generateBOMJSON,
    generateSeligDAT,
    generateMATLABScript,
    busState,
    ribCount
  ]);

  const handleCopy = () => {
    navigator.clipboard.writeText(currentArtifact.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([currentArtifact.content], { type: `${currentArtifact.mime};charset=utf-8` });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = currentArtifact.name;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-900/90 border border-teal-500/30 rounded-2xl p-5 shadow-2xl backdrop-blur-md space-y-5">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-gradient-to-br from-indigo-500/20 to-teal-500/20 border border-indigo-500/40 rounded-xl text-indigo-400">
            <Boxes className="w-6 h-6 animate-pulse" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-bold text-white tracking-wide">
                Экспорт Инженерных Артефактов (CAD / CAM / Autopilot Autogen)
              </h3>
              <span className="px-2 py-0.5 rounded-full text-[10px] font-mono font-semibold bg-indigo-500/10 text-indigo-300 border border-indigo-500/30">
                PRODUCER V2.4
              </span>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Прямая конвертация расчётной аэродинамической модели в файлы параметров автопилотов, чертежи DXF для лазера и 3D-модели
            </p>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopy}
            className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs text-slate-200 border border-slate-700 flex items-center gap-1.5 transition-all"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-teal-400" />}
            {copied ? 'Скопировано!' : 'Копировать'}
          </button>
          <button
            onClick={handleDownload}
            className="px-3.5 py-1.5 rounded-lg bg-gradient-to-r from-teal-600 to-indigo-600 hover:from-teal-500 hover:to-indigo-500 text-xs text-white font-medium flex items-center gap-1.5 transition-all shadow-lg"
          >
            <Download className="w-3.5 h-3.5" />
            Скачать {currentArtifact.ext}
          </button>
        </div>
      </div>

      {/* Artifact Category Selector */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
        <button
          onClick={() => setSelectedFormat('ardupilot_param')}
          className={`p-3 rounded-xl border text-left transition-all ${
            selectedFormat === 'ardupilot_param'
              ? 'bg-teal-950/60 border-teal-500 text-white shadow-lg'
              : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="font-semibold text-xs text-teal-300 flex items-center gap-1.5">
              <Cpu className="w-3.5 h-3.5" /> ArduPilot
            </span>
            <span className="text-[10px] font-mono bg-teal-500/10 text-teal-400 px-1.5 py-0.5 rounded">.param</span>
          </div>
          <p className="text-[11px] text-slate-400">ПИД коэффициенты, скоростные лимиты и L1 навигация</p>
        </button>

        <button
          onClick={() => setSelectedFormat('px4_params')}
          className={`p-3 rounded-xl border text-left transition-all ${
            selectedFormat === 'px4_params'
              ? 'bg-teal-950/60 border-teal-500 text-white shadow-lg'
              : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="font-semibold text-xs text-cyan-300 flex items-center gap-1.5">
              <Sliders className="w-3.5 h-3.5" /> PX4 Autopilot
            </span>
            <span className="text-[10px] font-mono bg-cyan-500/10 text-cyan-400 px-1.5 py-0.5 rounded">.params</span>
          </div>
          <p className="text-[11px] text-slate-400">FW_PR_P / FW_RR_P и профиль АКБ для QGroundControl</p>
        </button>

        <button
          onClick={() => setSelectedFormat('dxf_ribs')}
          className={`p-3 rounded-xl border text-left transition-all ${
            selectedFormat === 'dxf_ribs'
              ? 'bg-indigo-950/60 border-indigo-500 text-white shadow-lg'
              : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="font-semibold text-xs text-indigo-300 flex items-center gap-1.5">
              <Scissors className="w-3.5 h-3.5" /> Чертежи DXF
            </span>
            <span className="text-[10px] font-mono bg-indigo-500/10 text-indigo-400 px-1.5 py-0.5 rounded">AutoCAD</span>
          </div>
          <p className="text-[11px] text-slate-400">Раскрой нервюр с отверстиями под лонжероны для ЧПУ</p>
        </button>

        <button
          onClick={() => setSelectedFormat('openscad_wing')}
          className={`p-3 rounded-xl border text-left transition-all ${
            selectedFormat === 'openscad_wing'
              ? 'bg-amber-950/60 border-amber-500 text-white shadow-lg'
              : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="font-semibold text-xs text-amber-300 flex items-center gap-1.5">
              <Boxes className="w-3.5 h-3.5" /> 3D OpenSCAD
            </span>
            <span className="text-[10px] font-mono bg-amber-500/10 text-amber-400 px-1.5 py-0.5 rounded">.scad</span>
          </div>
          <p className="text-[11px] text-slate-400">Параметрическая 3D модель консоли для STL/STEP</p>
        </button>

        <button
          onClick={() => setSelectedFormat('inav_cli')}
          className={`p-3 rounded-xl border text-left transition-all ${
            selectedFormat === 'inav_cli'
              ? 'bg-teal-950/60 border-teal-500 text-white shadow-lg'
              : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="font-semibold text-xs text-teal-300 flex items-center gap-1.5">
              <FileCode className="w-3.5 h-3.5" /> INAV CLI
            </span>
            <span className="text-[10px] font-mono bg-teal-500/10 text-teal-400 px-1.5 py-0.5 rounded">.txt</span>
          </div>
          <p className="text-[11px] text-slate-400">Скрипт командной строки для крыла в INAV Configurator</p>
        </button>

        <button
          onClick={() => setSelectedFormat('wiring_bom_json')}
          className={`p-3 rounded-xl border text-left transition-all ${
            selectedFormat === 'wiring_bom_json'
              ? 'bg-purple-950/60 border-purple-500 text-white shadow-lg'
              : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="font-semibold text-xs text-purple-300 flex items-center gap-1.5">
              <FileSpreadsheet className="w-3.5 h-3.5" /> Спецификация BOM
            </span>
            <span className="text-[10px] font-mono bg-purple-500/10 text-purple-400 px-1.5 py-0.5 rounded">.json</span>
          </div>
          <p className="text-[11px] text-slate-400">Полный ведомость комплектующих (ESC, AWG, АКБ, мотор)</p>
        </button>

        <button
          onClick={() => setSelectedFormat('matlab_simulink')}
          className={`p-3 rounded-xl border text-left transition-all ${
            selectedFormat === 'matlab_simulink'
              ? 'bg-orange-950/60 border-orange-500 text-white shadow-lg'
              : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="font-semibold text-xs text-orange-300 flex items-center gap-1.5">
              <FileText className="w-3.5 h-3.5" /> MATLAB 6-DoF
            </span>
            <span className="text-[10px] font-mono bg-orange-500/10 text-orange-400 px-1.5 py-0.5 rounded">.m</span>
          </div>
          <p className="text-[11px] text-slate-400">Матрицы состояния A/B, тензоры инерции и собственные моды</p>
        </button>

        <button
          onClick={() => setSelectedFormat('dat_selig')}
          className={`p-3 rounded-xl border text-left transition-all ${
            selectedFormat === 'dat_selig'
              ? 'bg-emerald-950/60 border-emerald-500 text-white shadow-lg'
              : 'bg-slate-950/60 border-slate-800 text-slate-400 hover:border-slate-700'
          }`}
        >
          <div className="flex items-center justify-between mb-1">
            <span className="font-semibold text-xs text-emerald-300 flex items-center gap-1.5">
              <Layers className="w-3.5 h-3.5" /> Selig .DAT
            </span>
            <span className="text-[10px] font-mono bg-emerald-500/10 text-emerald-400 px-1.5 py-0.5 rounded">XFLR5</span>
          </div>
          <p className="text-[11px] text-slate-400">Нормализованные координаты для XFLR5, XFOIL и SolidWorks</p>
        </button>
      </div>

      {/* Parametric Modifiers (for DXF / CAD / 3D) */}
      {(selectedFormat === 'dxf_ribs' || selectedFormat === 'openscad_wing') && (
        <div className="bg-slate-950 p-3.5 rounded-xl border border-slate-800 grid grid-cols-1 md:grid-cols-3 gap-3 text-xs">
          <div className="space-y-1">
            <div className="flex justify-between text-slate-400 font-mono">
              <span>Количество нервюр:</span>
              <span className="text-teal-400 font-bold">{ribCount} шт</span>
            </div>
            <input
              type="range"
              min="3"
              max="16"
              value={ribCount}
              onChange={(e) => setRibCount(Number(e.target.value))}
              className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-teal-500"
            />
          </div>

          <div className="space-y-1">
            <div className="flex justify-between text-slate-400 font-mono">
              <span>Положение лонжерона:</span>
              <span className="text-indigo-400 font-bold">{sparPositionPct}% хорды</span>
            </div>
            <input
              type="range"
              min="15"
              max="45"
              value={sparPositionPct}
              onChange={(e) => setSparPositionPct(Number(e.target.value))}
              className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-indigo-500"
            />
          </div>

          <div className="space-y-1">
            <div className="flex justify-between text-slate-400 font-mono">
              <span>Диаметр карбоновой трубки:</span>
              <span className="text-amber-400 font-bold">{sparHoleDiaMm} мм</span>
            </div>
            <input
              type="range"
              min="4"
              max="20"
              value={sparHoleDiaMm}
              onChange={(e) => setSparHoleDiaMm(Number(e.target.value))}
              className="w-full h-1.5 bg-slate-800 rounded-lg appearance-none cursor-pointer accent-amber-500"
            />
          </div>
        </div>
      )}

      {/* Code Viewer Panel */}
      <div className="relative rounded-xl overflow-hidden border border-slate-800 bg-slate-950">
        <div className="flex items-center justify-between px-4 py-2 bg-slate-900 border-b border-slate-800 text-xs">
          <span className="font-mono text-slate-300 flex items-center gap-2">
            <FileCode className="w-4 h-4 text-teal-400" />
            {currentArtifact.name}
          </span>
          <span className="text-[10px] font-mono text-slate-500">
            {currentArtifact.content.split('\n').length} строк | {(new Blob([currentArtifact.content]).size / 1024).toFixed(1)} КБ
          </span>
        </div>

        <pre className="p-4 text-[11px] font-mono text-emerald-400 overflow-x-auto max-h-80 leading-relaxed scrollbar-thin scrollbar-thumb-slate-700">
          {currentArtifact.content}
        </pre>
      </div>

      {/* Quick Integration Guidance */}
      <div className="p-3 bg-slate-950/70 border border-slate-800 rounded-xl flex items-center justify-between gap-3 text-xs">
        <div className="flex items-center gap-2.5 text-slate-400">
          <AlertCircle className="w-4 h-4 text-teal-400 shrink-0" />
          <span>
            {selectedFormat === 'ardupilot_param' && 'Загрузите скачанный файл в Mission Planner через меню Config -> Full Parameter Tree -> Load from file.'}
            {selectedFormat === 'px4_params' && 'Импортируйте файл параметров в QGroundControl в разделе Vehicle Setup -> Parameters -> Tools -> Load from file.'}
            {selectedFormat === 'inav_cli' && 'Скопируйте скрипт и вставьте в терминал вкладки CLI в INAV Configurator, затем нажмите Enter.'}
            {selectedFormat === 'dxf_ribs' && 'Файл DXF совместим со станками лазерной резки (LightBurn, LaserCAD) и SolidWorks/AutoCAD.'}
            {selectedFormat === 'openscad_wing' && 'Откройте в OpenSCAD (F5 для рендера, F6 для генерации STL) для 3D печати консоли.'}
            {selectedFormat === 'wiring_bom_json' && 'Спецификация содержит точные сечения проводов и ампераж регуляторов для сборщиков.'}
            {selectedFormat === 'matlab_simulink' && 'Запустите скрипт в MATLAB для получения передаточных функций W(s) и корней устойчивости.'}
            {selectedFormat === 'dat_selig' && 'Файл готов для импорта в XFLR5 через меню Foil -> Open Selig Coordinates.'}
          </span>
        </div>
      </div>
    </div>
  );
};
